using FollowerForge.Domain;
using FollowerForge.ModManagers;

namespace FollowerForge.Tests;

public sealed class Mo2DiskPriorityTests
{
    [Fact]
    public void Modlist_DiskHighestFirst_IsReturnedLowestFirst()
    {
        var path = Path.GetTempFileName();
        try
        {
            // MO2 Profile::doWriteModlist serializes reverse priority order.
            File.WriteAllText(path, "# generated by MO2\n+Winning patch\n-Disabled\n+Base mod\n");
            Assert.Equal(new[] { "Base mod", "Winning patch" }, PluginLists.ParseMo2ModList(path));
        }
        finally { File.Delete(path); }
    }

    [Fact]
    public void Modlist_CustomPaths_ResolvesHighestPriorityPluginAndTexture()
    {
        var root = Path.Combine(Path.GetTempPath(), "ff_priority_" + Guid.NewGuid().ToString("N"));
        try
        {
            var data = Path.Combine(root, "Steam elsewhere", "Skyrim", "Data");
            var mods = Path.Combine(root, "External mods");
            var profile = Path.Combine(root, "External profiles", "Selected profile");
            Directory.CreateDirectory(profile);
            foreach (var (folder, content) in new[]
            {
                (data, "game"),
                (Path.Combine(mods, "Base mod"), "base"),
                (Path.Combine(mods, "Winning patch"), "winner"),
                (Path.Combine(mods, "Disabled"), "disabled"),
            })
            {
                Directory.CreateDirectory(Path.Combine(folder, "textures"));
                File.WriteAllText(Path.Combine(folder, "Demo.esp"), content);
                File.WriteAllText(Path.Combine(folder, "textures", "face.dds"), content);
            }
            var modlist = Path.Combine(profile, "modlist.txt");
            File.WriteAllText(modlist, "+Winning patch\n-Disabled\n+Base mod\n");
            var env = new EnvironmentSnapshot
            {
                Manager = ModManagerKind.Mo2,
                ManagerLabel = "Mod Organizer 2",
                GameRootPath = Path.GetDirectoryName(data)!,
                GameDataPath = data,
                PluginDataPath = Path.Combine(root, "view"),
                InstancePath = Path.Combine(root, "MO2 instance"),
                StagingPath = mods,
                ProfilesPath = Path.GetDirectoryName(profile)!,
                RuntimePluginsTxtPath = Path.Combine(profile, "plugins.txt"),
                Mo2ModPriority = PluginLists.ParseMo2ModList(modlist),
            };
            Assert.Equal("winner", File.ReadAllText(Mo2PathResolver.ResolvePlugin(env, "Demo.esp")!));
            Assert.Equal("winner", File.ReadAllText(Mo2PathResolver.ResolveRelative(env, "textures/face.dds")!));
        }
        finally { if (Directory.Exists(root)) Directory.Delete(root, recursive: true); }
    }
}
